version: "1.0"
info:
  model: int-scaffold
packages:
- name: WmSalesforceRESTProvider
  version: 12.0.0.0.16
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: SIQA_GIT_2025Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: project.siqa_git_2025.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:RestConnAlias2003
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: project.siqa_git_2025.integrations:Test_RestConnector
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: project.siqa_git_2025.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.operations.actions:TestRest
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: project.siqa_git_2025.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_2025Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.1.0.0.805
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.1.0.0.805
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.805
configurationVariables:
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth.consumerId
  : 3MVG9pe2TCoA1Pf6F9PMP1LEDsuYm6pfL6T8OD7YSQUQsx36uZNIjUH3BCzBZ8lgStKaUEITogkQ7hNByxJjv
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : sa
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}X4QCAWgjWkTdMQvFA5XaqGmK1wuN3U1rA1B0VhuZoUw="
  ? iscloudstreamsconnectorservice.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..operations..actions:TestRest.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.socketLinger
  : "-1"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.tcpNoDelay
  : "false"
  jdbcfunc.SAPTxStore.failFastMode: false
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "1433"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth.accessToken
  : "{AES}bzO+KX5xKoE0CKrgiYZryC5gsfW9FyC4gAfOF/ZABz7yyhKO+UgGOoVuBsdPxoRhC8+8SZl7Mp60ASGR0uoVoEtfSoo17E+5ChAuS8VZ8Tk7z9jlMSlrEh8w238yHnoAHOc5LI/4yCFOH8ykmKMjNmmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.scope
  : offline_access api refresh_token
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.timeoutType
  : auto
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.poolable
  : "true"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.keepAliveInterval
  : "300000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : tcp
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth.consumerSecret
  : "{AES}8bc8/WHaL3dph5PtuD02009Twi827NgOvyLy8mkfF31b5gfhajCNPAG/2OxW9yx8fPwx12ONSDGw1NRjVAxIemmK1wuN3U1rA1B0VhuZoUw="
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MSSQL
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.reuseAddr
  : "false"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}X4QCAWgjWkTdMQvFA5XaqGmK1wuN3U1rA1B0VhuZoUw="
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : sa
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : 9.60.195.99
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "false"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : tcp
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.connectTimeout
  : "30000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.idleTimeout
  : "-1"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : 9.60.195.99
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cx.grant_type
  : refresh_token
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.retryCount
  : "4"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.connectionEnabled
  : "true"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? iscloudstreamsconnectorservice.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..operations..actions:TestRest.connectionAlias
  : project.siqa_git_2025.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:RestConnAlias2003
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.refreshAccessToken
  : "true"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.blockingTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.providerUrl
  : https://d0o000001qr6keac-dev-ed.my.salesforce.com
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.authorizationHeaderPrefix
  : Bearer
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.oauth_v20.refreshToken
  : "{AES}iVEYOEICT1x7P9RL3dwVv0pQv1IODTw0Qm0vrSHPR8I0XZ0/KrBE7WODHo6AzR1637cjFT8vTWSxMJCq+8Fwx23ujlk6B/pLD2FnkHRwbbHw+MNh1fzWP9ra98cky/Z+"
  ? artConnection.SIQA_GIT_2025Project.project.siqa_git_2025.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1433"
  ? cloudstreamsconnection.project..siqa_git_2025..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:RestConnAlias2003.minimumPoolSize
  : "1"
